[2024-10-17T21:39:12.207+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-17T21:39:12.211+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: taskgroup_and_labels_pipeline.determine_branch scheduled__2024-10-16T00:00:00+00:00 [queued]>
[2024-10-17T21:39:12.213+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: taskgroup_and_labels_pipeline.determine_branch scheduled__2024-10-16T00:00:00+00:00 [queued]>
[2024-10-17T21:39:12.213+0100] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-17T21:39:12.217+0100] {taskinstance.py:2888} INFO - Executing <Task(BranchPythonOperator): determine_branch> on 2024-10-16 00:00:00+00:00
[2024-10-17T21:39:12.219+0100] {standard_task_runner.py:72} INFO - Started process 4645 to run task
[2024-10-17T21:39:12.222+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'taskgroup_and_labels_pipeline', 'determine_branch', 'scheduled__2024-10-16T00:00:00+00:00', '--job-id', '259', '--raw', '--subdir', 'DAGS_FOLDER/taskgroups_edgelabels.py', '--cfg-path', '/var/folders/nl/1x330z2x7yzb268yb0bbvjcr0000gn/T/tmpbb9g_25a']
[2024-10-17T21:39:12.223+0100] {standard_task_runner.py:105} INFO - Job 259: Subtask determine_branch
[2024-10-17T21:39:12.236+0100] {task_command.py:467} INFO - Running <TaskInstance: taskgroup_and_labels_pipeline.determine_branch scheduled__2024-10-16T00:00:00+00:00 [running]> on host mujtabas-macbook-pro.local
[2024-10-17T21:39:12.258+0100] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ali' AIRFLOW_CTX_DAG_ID='taskgroup_and_labels_pipeline' AIRFLOW_CTX_TASK_ID='determine_branch' AIRFLOW_CTX_EXECUTION_DATE='2024-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-16T00:00:00+00:00'
[2024-10-17T21:39:12.258+0100] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-17T21:39:12.263+0100] {baseoperator.py:405} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-10-17T21:39:12.264+0100] {python.py:240} INFO - Done. Returned value was: Grouping.groupby_region_smoker
[2024-10-17T21:39:12.264+0100] {branch.py:38} INFO - Branch into Grouping.groupby_region_smoker
[2024-10-17T21:39:12.264+0100] {skipmixin.py:230} INFO - Following branch {'Grouping.groupby_region_smoker'}
[2024-10-17T21:39:12.267+0100] {skipmixin.py:278} INFO - Skipping tasks [('Filtering.filter_by_region', -1), ('Filtering.filter_bmi_smoker_charges', -1)]
[2024-10-17T21:39:12.273+0100] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-17T21:39:12.273+0100] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=taskgroup_and_labels_pipeline, task_id=determine_branch, run_id=scheduled__2024-10-16T00:00:00+00:00, execution_date=20241016T000000, start_date=20241017T203912, end_date=20241017T203912
[2024-10-17T21:39:12.283+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-17T21:39:12.291+0100] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-17T21:39:12.291+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
