[2024-10-16T13:31:01.689+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-16T13:31:01.692+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_pipeline.read_csv_file scheduled__2024-10-15T00:00:00+00:00 [queued]>
[2024-10-16T13:31:01.694+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_pipeline.read_csv_file scheduled__2024-10-15T00:00:00+00:00 [queued]>
[2024-10-16T13:31:01.694+0100] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-16T13:31:01.699+0100] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): read_csv_file> on 2024-10-15 00:00:00+00:00
[2024-10-16T13:31:01.701+0100] {standard_task_runner.py:72} INFO - Started process 68625 to run task
[2024-10-16T13:31:01.703+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'python_pipeline', 'read_csv_file', 'scheduled__2024-10-15T00:00:00+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/python_pipeline.py', '--cfg-path', '/var/folders/nl/1x330z2x7yzb268yb0bbvjcr0000gn/T/tmp8jvjeadw']
[2024-10-16T13:31:01.704+0100] {standard_task_runner.py:105} INFO - Job 183: Subtask read_csv_file
[2024-10-16T13:31:01.717+0100] {task_command.py:467} INFO - Running <TaskInstance: python_pipeline.read_csv_file scheduled__2024-10-15T00:00:00+00:00 [running]> on host mujtabas-macbook-pro.local
[2024-10-16T13:31:01.735+0100] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ali' AIRFLOW_CTX_DAG_ID='python_pipeline' AIRFLOW_CTX_TASK_ID='read_csv_file' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-15T00:00:00+00:00'
[2024-10-16T13:31:01.736+0100] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-16T13:31:01.742+0100] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/mujtabaalimalik/airflow/dags/python_pipeline.py", line 15, in read_csv_file
    df = pd.read_csv('/Users/loonycorn/airflow/datasets/insurance.csv')
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/Users/loonycorn/airflow/datasets/insurance.csv'
[2024-10-16T13:31:01.746+0100] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=python_pipeline, task_id=read_csv_file, run_id=scheduled__2024-10-15T00:00:00+00:00, execution_date=20241015T000000, start_date=20241016T123101, end_date=20241016T123101
[2024-10-16T13:31:01.748+0100] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-16T13:31:01.749+0100] {standard_task_runner.py:124} ERROR - Failed to execute job 183 for task read_csv_file ([Errno 2] No such file or directory: '/Users/loonycorn/airflow/datasets/insurance.csv'; 68625)
Traceback (most recent call last):
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/mujtabaalimalik/airflow/dags/python_pipeline.py", line 15, in read_csv_file
    df = pd.read_csv('/Users/loonycorn/airflow/datasets/insurance.csv')
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/opt/miniconda3/envs/airflow/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/Users/loonycorn/airflow/datasets/insurance.csv'
[2024-10-16T13:31:01.763+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-16T13:31:01.768+0100] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-16T13:31:01.768+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
